### ISSUE TITLE
Disable Flex Display for Smaller Screens (Regarding the flex code used to vertically center elements)

### ISSUE THREAD

**Issue by shelbourn** [shelbourn/FreeCodeCamp_Challenges#14]
Figure out a way to disable the flex display for smaller screens. Currently with a flex display applied to the 'Bio' section and to the Bootstrap Row within the 'Bio' section, the Row stays at full viewport width when the window is scaled down. This means that the Bootstrap grid system doesn't break due to the flex display. This is because Bootstrap xs columns have a fixed width.

**Comment by shelbourn** [comment]
Fixed with the following code:

``` css
/* Disable Flex display on screen sizes 1000px wide or smaller -- Need this otherwise the Bootstrap grid system will not snap to sm-12 or xs-12 for smaller devices */

@media (max-width: 1000px) {
    .row.bio-row-center {
        display: block;
    }
}
```
