### ISSUE TITLE
Change vh or vw for Cover setting in Portfolio 2

### ISSUE THREAD

**Issue by shelbourn** [shelbourn/FreeCodeCamp_Challenges#6]
Change the vw or vh setting in the Portfolio 2 CSS to make the cover page appear full width and full height

**Comment by shelbourn** [comment]
This code snippet fixed this issue, however it created a new issue with the container formatting within the cover page:

BEFORE --

``` css
.wide {
    height: 100vh;
  height:calc(100% - 1px);
    background:
        linear-gradient(
        rgba(255,255,255,0.25),
        rgba(255,255,255,0.25)
        ),  url('https://raw.githubusercontent.com/shelbourn/FreeCodeCamp_Challenges/master/Matt_Shelbourn_Portfolio_Cover.jpg');
  background-size: cover;
    background-position: center;
}
```

AFTER --

``` css
.wide {
    height: 100vh;
  /* height:calc(100% - 1px); REMOVED TO MAKE COVER FULL VIEWPORT HEIGHT. LOST THE BOTTOM CONTAINER THOUGH. NEED TO FIX */
    background:
        linear-gradient(
        rgba(255,255,255,0.25),
        rgba(255,255,255,0.25)
        ),  url('https://raw.githubusercontent.com/shelbourn/FreeCodeCamp_Challenges/master/Matt_Shelbourn_Portfolio_Cover.jpg');
  background-size: cover;
    background-position: center;
}
```
