### ISSUE TITLE
Page Section Backgrounds

### ISSUE THREAD

**Issue by shelbourn** [shelbourn/FreeCodeCamp_Challenges#9]
Pick material background textures for page sections.

Currently, I am using linear gradients for the section backgrounds, but I don't really like them that much.

Current Background --

``` css
.bio-wide {
    height:93vh; /* NEED THIS HEIGHT MEASUREMENT TO MAKE EVERY COVER PAGE (EXCEPT THE LANDING PAGE) TO FIT 100% WIDTH AND HEIGHT */
    /* height:calc(100% - 1px); COMMENTING THIS OUT SO THAT I CAN HAVE THE SECTION FILL THE ENTIRE HEIGHT AND WIDTH OF THE VIEWPORT */
    background:
        linear-gradient(
        rgba(255,255,255,1.0),
        rgba(0,0,0,0.7)
        );
    background-size: cover;
    background-position: center;
}
```
